### PR TITLE
working draft of final geostacks earthcube notebook

### PR DESCRIPTION
**Pull request by espg**
Mostly filled in text for the narrative headings. Still working on merging in the cells from a few notebooks to form a cohesive story. but think that I can see a reasonable end point.

TODO:

- [x] Update Affiliations, emails, orcids, etc
- [ ] Finalize narrative text (spell check, links, feedback, etc)
- [x] Update Intake catalog for google cloud, collection 1 
- [x] Merge intake/dask cells from other notebooks
- [x] Integrate S3 search with fetch using intake
- [ ] Science demo: Grab time series for single path row combo, extract cloud cover percent as new output
- [ ] __repr__ method (if time)

@whyjz thinking of moving the UI code into the library so it's just an import/call to plot -- thoughts?

### CODE REVIEW

**Comment by whyjz** [comment]
Thanks Shane! This looks great. I think maybe we can work on this branch a bit more and merge the PR after most things on the to-dos are done. What do you think?

Totally agree with moving the UI class into the library. I can do that quickly.

**Comment by espg** [comment]
@whyjz sounds great, thanks for taking the UI! Testing the new intake catalog now...

**Comment by whyjz** [comment]
Also @espg and @fperez do you still want to keep your old branches?

**Comment by espg** [comment]
@whyjz what do you think about modifying how s3search encodes data? Right now, it does:
```
s3_prefix, scene_list = ls8.search_s3(cpanel.pr_selection)
```
which returns a s3 prefix (e.g. `'c1/L8/082/233/LC08_L1TP_'`, and data frame with the longer prefix value (e.g. `'c1/L8/082/233/LC08_L1TP_082233_20200531_20200608_01_T1/'`). The intake catalog needs path, row, and band. The old version also took year and doy to construct the full s3 bucket address... but that isn't enough because of the need for processing date. 

Right now the intake catalog for google cloud expects path, row, and base-- base is:
```
selection.prefix.iloc[2][14:]
```
'LC08_L1TP_082233_20200531_20200608_01_T1/'
```

We could build by just grabbing the `20200608` part above, or the whole string works too... can we change the column output a bit to avoid string slicing later on?

```

**Comment by whyjz** [comment]
@espg It's doable I think, but I wonder how generic this strategy is given that the method name is `search_s3` instead of `search_s3_processing_date`. What about creating another method that calls `search_s3` and does this specific task?

**Comment by espg** [comment]
@whyjz fine to delete the old branches... do you know how? I thought I deleted the 'ecube' branch on the command line, but it didn't propagate to github and I'm not sure how to...

**Comment by whyjz** [comment]
@espg [here](https://stackoverflow.com/questions/2003505/how-do-i-delete-a-git-branch-locally-and-remotely) is the answer for deleting the remote branch from the command line, but what I mostly do is actually using the Github interface... click where the red arrow points at and you'll find how!
ScrSelection_020

**Comment by espg** [comment]
@whyjz that could work-- I was thinking less of removing or changing the existing columns, and was curious if there was any reason to not add additional columns to that data structure

**Comment by whyjz** [comment]
Okay so here's a quick workaround -- now there are two fields about time: `arc_time` is the acquisition time and `prc_time` is the processing time. They are both a `date` object so you might need to do some string conversion for Intake to digest.
ScrSelection_021

**Comment by espg** [comment]
@whyjz do you think its feasible to modify s3search to work on either a list or array idx values? I'm thinking if you want to select the closest granule to your query point in time, then you want to check for the acquisition times of multiple scenes to figure out the closest match (as opposed to the most spatially centered)

**Comment by whyjz** [comment]
@espg do you mean whether we can search the S3 bucket using more than 1 P/R selections at once? So that we know which P/R has the granule with the most desired acquisition time?

**Comment by espg** [comment]
@whyjz yes, exactly. 

I'm tempted to say that we should actually just call s3search automatically when we do that pathrow query, and extract times so that we can sort the matches by acquisition time... although that would require modifying the query method to take either a time or time slice to keep the results reasonable. For now though, just having the method check for single vs multiple p/r values and loop when calling boto would be useful >.>

**Comment by whyjz** [comment]
@espg ok I've updated the `s3_search` method so it accepts a list of indices. An example is on`EarthCube_meeting.ipynb`!

**Comment by espg** [comment]
@whyjz great, I'll have a look!

I've been working on getting a method to select the closest scene, and pandas has a great convenience method... but it'll require some changes. The convenience method assumes that the dataframe is indexed as datetimeindex, which should be straightforward (just `setindex("acq_time")`)... however there are two complications, which are really the same complication. To use `get_loc(dt, method='nearest')`, pandas wants the index to be unique. The s3search grabs duplicates-- mainly RT (near real time scenes) which have the same acquisition datetime representation. I think a check on the tier column (if tier == "RT") can be used to set a small offset on the datetime object--say, a minute? This should be fine because the meta data is pretty coarse (there's no actual time, just day/month/year, so adding an offset does't really change anything). The other cause of duplicates is rarer... sometimes a scene is reprocessed, and re-posted, giving it the same 'tier', and the same acquisition time, with a different processing date (so it's not a 'true' duplicate). My though on this is  to just drop these entries; pandas will let you remove duplicate index values and keep the first or last entry (last would be the later processed file which is presumably preferred)...

Specifics aside, are you generally supportive of making s3search use datetime as in index, instead of the plain integer list?

**Comment by espg** [comment]
ok, just added (unique) time indices for s3search... working on an updated example for how it works now...

**Comment by whyjz** [comment]
@espg thanks for the update! Manually adding a minute to the `RT` scenes should work here, but in the long run, I think it is also worth introducing a new argument to `s3_search` so users can specify their preferences for search results. Here are some examples:
- Do not search for `RT` scenes at all
- Search `T1` first, and if `T1` is not available, then include `RT`
- Include both `T1` and `RT` (original)

The reason I used the `date` class instead of the `datetime` class is that printing a `datetime` project in pandas frame throws a lot of `00:00:00`s, which I don't quite like :P . It does look that we need it for unique query result on the notebook though. Maybe we can talk about this to see if there are other ways to deal with the unique query after the EC meeting!

Also, in general I am not a fan of using an object as an index label... I typically use integer or string for that because slicing/selecting data would be less error-prone than an object label. For example, if `scene_list` looks like this:
ScrSelection_022
`scene_list[datetime(2013, 3, 1):datetime(2013, 4, 1)]` works here (and returns 3 entries), but `scene_list[datetime(2013, 3, 19)]` throws an error for unknown reason.

One way to mitigate this is maybe the use of a serial date number? Like
```
delta = date - reference_date
index label = delta.days()
```

**Comment by espg** [comment]
@whyjz was working on an updated notebook that addresses some of these issues... checkout cells 13 and 14 for subsetting or filtering RT scenes and let me know what you think. 

I need to think a bit more on the datetime index... I think that the index is actually stored as numpy timestamps, rather than just objects but I would need to check on that. I also remember a there being a flexible way of accessing datetime indices-- where if you pass in a month, it will just return all entries for that month, same with a day, etc... I'm hoping that functionality is still something that can be enabled, and hasn't been removed. That would just let us pass the the next 'time unit' up and get the approximate match or matches. There is a closest in time method (cell 8), but it's a bit verbose, so it would be better if we can avoid that. There are some subtle differences between how pandas and datetime handle time, but I need to recharge before diving in.

6e9f40b is my last commit for tonight-- most of the code is there, but more narrative text in and around the cells would be good, along with better plotting of clouds and an actual percentage coverage calculation. I'll get to those tomorrow afternoon. I think I'll probably submit the binder link to NSF EarthCube in a few minutes, and just pin the binder build to this branch, so if we make minor changes tomorrow (or later), they'll just get pulled in, as long as we don't break the build system >.>

**Comment by whyjz** [comment]
Cool! based on the current plan, what do you think if we merge and close this PR but continue to work on this branch. So the current notebook status is archived into the `main` branch like a tag. We can open another PR for the remaining to-dos.

That fancy monthly slicing sounds cool, and I am keen to know more about that!

One quick question @espg : what is `i` in the last cell of the EC notebook?

**Pull request merged**
